[build]
  base = "frontend"
  command = "ng build --configuration=netlify"
  publish = "dist/frontend/browser"

# Headers for proper MIME types for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8" 
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for other static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "https://helenskitchen.onrender.com/api/:splat"
  status = 200

# Root redirect to menu
[[redirects]]
  from = "/"
  to = "/menu"
  status = 301

# SPA fallback for Angular routes (exclude static files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false